name: flutter_onlooker
description: A state management library which provides a simple solution for updating state and navigation.
version: 1.1.0
homepage: https://github.com/phimary/flutter_onlooker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
